### ISSUE TITLE
Problems about ‘Extending DCNv2 for Vision Foundation Models’

### ISSUE THREAD

**Issue by ChaseMonsterAway** [OpenGVLab/InternImage#63]
Hi, I have a problem with the point that "DCNv2 is usually used as an extension to regular convolutions, loading pre-trained weights of regular convolutions and fine-tuning for better performance, which is not exactly suitable for large-scale vision foundation models that need to be trained from scratch."

It's a little difficult for me to understand why. I checked the DCNV2 and found the performance on ImageNet to be pretty good. Can you give me some advice to understand it?

**Comment by czczup** [comment]
Thanks for your attention. DCNv2 is usually employed in ResNet series, for example, ResNet-50. These models are marked as ResNet-DCN in various papers, which inherit the ImageNet pretrained weights of ResNet, and only replace some layers of ResNet from regular dense convolution to DCNv2 during fine-tuning downstream tasks, such as object detection and semantic segmentation. 
Therefore, DCNv2 often plays a role of an efficient plugin (don't need ImageNet pretraining) for enhancing the performance of downstream tasks, rather than a component to build large-scale vision foundation models.

**Comment by ChaseMonsterAway** [comment]
> Thanks for your attention. DCNv2 is usually employed in ResNet series, for example, ResNet-50. These models are marked as ResNet-DCN in various papers, which inherit the ImageNet pretrained weights of ResNet, and only replace some layers of ResNet from regular dense convolution to DCNv2 during fine-tuning downstream tasks, such as object detection and semantic segmentation. Therefore, DCNv2 often plays a role of an efficient plugin (don't need ImageNet pretraining) for enhancing the performance of downstream tasks, rather than a component to build large-scale vision foundation models.

Thank you for your explanation. In other words, it is not DCNv2 itself that is not ready for large-scale vision foundation models, but the traditional usage is not. If we always train a DCNv2-based model from scratch, it will be "large-scale vision ready". Am I correct?
